### PR TITLE
Target & Verify action should append to Jira labels, not overwrite.

### PR DESCRIPTION
**Pull request by mitchell-as**
<table>
<td>
  <a href="https://activestatef.atlassian.net/browse/DX-3152" title="DX-3152" target="_blank">BugDX-3152</a>  "Target & Verify" automation removes an existing "Found_By_QA_Automation" label
  </td></table>
  <br />

### CODE REVIEW

**Comment by mitchell-as** [comment]
Tested by adding a label to the JIRA issue, then running Target & Verify, and checking that "WasNextFeasible" was appended instead of overwriting the existing label.

**Comment by mitchell-as** [comment]
image

**Comment by mitchell-as** [comment]
@Naatan ping

**Comment by mitchell-as** [comment]
The concern you raised may look problematic based on the diff GitHub shows, but the troublesome line is here: https://github.com/ActiveState/cli/pull/3588/files#diff-2224e300e5d1da6fa67f6cf4cfc1d6b288f60bda27d6d0181bce500076850273R192. We need to initialize the struct with the current set of labels if we want to append to it. Otherwise, we're appending to an empty list, which will overwrite the current label.

I think we're fine.

**Review by Naatan — APPROVED** [review]

**Pull request merged**
