### PR TITLE
Added state use reset subcommand.

### PR DESCRIPTION
**Pull request by mitchell-as**
<table>
<td>
  <a href="https://activestatef.atlassian.net/browse/DX-1011" title="DX-1011" target="_blank">StoryDX-1011</a>  `state use reset` does not work
  </td></table>
  <br />
 

Cherry picked all commits from https://github.com/ActiveState/cli/pull/1866 to `beta` branch, and created this PR for merging into `beta` branch.

### CODE REVIEW

**Review by MDrakos — APPROVED** [review]

**Comment by mitchell-as** [comment]
@Naatan I do not have authorization to merge this, so please do so when you have the chance. Thanks.

**Comment by Naatan** [comment]
@mitchell-as what's it showing you? I can't see why it wouldn't let you merge.

**Comment by mitchell-as** [comment]
@Naatan Merging is blocked
The base branch restricts merging to authorized users. [Learn more about protected branches.](https://docs.github.com/articles/about-protected-branches/)

**Comment by Naatan** [comment]
Oooh it's cause you're targeting beta. You need to target master instead. Nothing goes straight to beta.

**Comment by mitchell-as** [comment]
master already has these changes. These changes were not cherry picked over to beta and/or release and are subsequently not in 0.34.

**Comment by Naatan** [comment]
That doesn't change our process. v0.34 is out, the boat has sailed on that one. If we want this in eg. v0.34.1 then we should set the fixVersion on Jira to that version and merge it to master. I will then take care of cherry picking it to beta once we do the next release.

I'm still working on documenting this process, hopefully this will start to make more sense soon.

Basically we just need to ensure the fixVersion is right, the rest of the development workflow is unchanged regardless of what version it goes out in.

**Comment by mitchell-as** [comment]
The original ticket has been updated with a new fix version. The PR is now irrelevant.

**Pull request closed without merging**
