### PR TITLE
Add session token

### PR DESCRIPTION
**Pull request by Naatan**
Interim release version: https://github.com/ActiveState/cli/pull/1463

### CODE REVIEW

**Review by mdrohmann — CHANGES_REQUESTED** [review]
It looks good, but the transitional State Tool should forward the session id to the installer.  I think that needs to happen here:
https://github.com/ActiveState/cli/blob/master/cmd/state-transition-update/main.go#L82

**Comment by Naatan** [comment]
> It looks good, but the transitional State Tool should forward the session id to the installer. I think that needs to happen here:
> https://github.com/ActiveState/cli/blob/master/cmd/state-transition-update/main.go#L82

I didn't think that would matter since it would only ever get invoked through the auto updater, which won't ever be fed this token. Am I missing something?

**Comment by mdrohmann** [comment]
> > It looks good, but the transitional State Tool should forward the session id to the installer. I think that needs to happen here:
> > https://github.com/ActiveState/cli/blob/master/cmd/state-transition-update/main.go#L82
> 
> I didn't think that would matter since it would only ever get invoked through the auto updater, which won't ever be fed this token. Am I missing something?

I think you are correct. The only exception would be that some-one is re-using the old install.sh / install.ps1 which (at some point) is targeting a transitional State Tool.  But who would do that?

**Review by mdrohmann — APPROVED** [review]

**Comment by Naatan** [comment]
> > > It looks good, but the transitional State Tool should forward the session id to the installer. I think that needs to happen here:
> > > https://github.com/ActiveState/cli/blob/master/cmd/state-transition-update/main.go#L82
> > 
> > 
> > I didn't think that would matter since it would only ever get invoked through the auto updater, which won't ever be fed this token. Am I missing something?
> 
> I think you are correct. The only exception would be that some-one is re-using the old install.sh / install.ps1 which (at some point) is targeting a transitional State Tool. But who would do that?

Yeah, and even if it did happen it wouldn't happen in a way that we'd be trying to inject a session token.

**Comment by mdrohmann** [comment]
> Yeah, and even if it did happen it wouldn't happen in a way that we'd be trying to inject a session token.

It could! After the proposed changes on the release channel merge via this line: https://github.com/ActiveState/cli/blob/4629c5300b7ebcbd32dfd70dbfb0bcbc8e0f0e93/installers/install.sh#L425

**Comment by Naatan** [comment]
> > Yeah, and even if it did happen it wouldn't happen in a way that we'd be trying to inject a session token.
> 
> It could! After the proposed changes on the release channel merge via this line:
> 
> https://github.com/ActiveState/cli/blob/4629c5300b7ebcbd32dfd70dbfb0bcbc8e0f0e93/installers/install.sh#L425

D'oh, good eye! Will do a followup PR.

**Pull request merged**
