### PR TITLE
Attempt to fix Auth integration tests.

### PR DESCRIPTION
**Pull request by mitchell-as**
<table>
<td>
  <a href="https://activestatef.atlassian.net/browse/DX-724" title="DX-724" target="_blank">BugDX-724</a>  Authentication int tests are failing
  </td></table>
  <br />

### CODE REVIEW

**Review by Naatan — CHANGES_REQUESTED** [review]
Looks like tests are still failing.

**Comment by mitchell-as** [comment]
Yeah, I didn't know how to cancel the review or put the PR back in draft status.

**Comment by Naatan** [comment]
It should be the same as when you tagged me, just click my name again and it'll untag me.

**Comment by Naatan** [comment]
Merged these changes into https://github.com/ActiveState/cli/pull/1735 as there was too much overlap.

**Pull request closed without merging**
