### PR TITLE
Do not parse verbose flags in shim args

### PR DESCRIPTION
**Pull request by mdrohmann**
https://www.pivotaltracker.com/story/show/176667499

### CODE REVIEW

**Review by MDrakos — CHANGES_REQUESTED** [review]
I believe cobra should be handling this for us here https://github.com/ActiveState/cli/blob/master/cmd/state/internal/cmdtree/shim.go#L43 but perhaps it's not being called any longer? I noticed that shim has a `--path` flag so disabling flag parsing may interfere with that. I'm not sure that `shim` logic should live in main. Can you take a look into this and see if `disableFlagParsing` is working as intended?

**Comment by mdrohmann** [comment]
The issue here, is that the check for verbose arguments is done even before the cmdtree is initialized.  So, this parsing is completely separate from cobra:


Here is where the cmdtree is initialized:
https://github.com/ActiveState/cli/blob/master/cmd%2Fstate%2Fmain.go#L168
And the verbose check is on line 102 above that.

**Comment by mdrohmann** [comment]
@Naatan The Windows shim also uses the double dash separator: https://github.com/ActiveState/cli/blob/master/assets%2Fshim%2Fshim.bat#L5

**Review by MDrakos — APPROVED** [review]
>The issue here, is that the check for verbose arguments is done even before the cmdtree is initialized. So, this parsing is completely separate from cobra

I see what you mean. I will defer to @Naatan on this one. I still feel that we should be handling the flags all in one place, but that should probably be it's own ticket.

**Review by Naatan — APPROVED** [review]

**Pull request merged**
