### PR TITLE
Use the latest OS runners for GitHub Actions.

### PR DESCRIPTION
**Pull request by mitchell-as**
<table>
<td>
  <a href="https://activestatef.atlassian.net/browse/DX-2729" title="DX-2729" target="_blank">TaskDX-2729</a>  Update our macOS CI runner to latest
  </td></table>
  <br />

### CODE REVIEW

**Comment by mitchell-as** [comment]
Test failures are either the usual timeouts or are known issues.

**Review by MDrakos — APPROVED** [review]
This looks good.

There are a fair amount of Windows failures. Are _all_ of them known or expected? I haven't been keeping as close an eye on the nightly failures to know. Many of them look new to me.

**Comment by mitchell-as** [comment]
You're right that those Windows failures are unreasonable. They weren't happening on the first run... I'll re-run them again and we'll see what happens.

**Comment by mitchell-as** [comment]
Okay, I reverted the windows image change and filed a ticket for it: https://activestatef.atlassian.net/browse/DX-2749. It turns out there are a number of minor output issues with `windows-latest`.

**Review by MDrakos — APPROVED** [review]

**Pull request merged**
