### PR TITLE
Do not autoupdate while a project is locked.

### PR DESCRIPTION
**Pull request by mitchell-as**
<table>
<td>
  <a href="https://activestatef.atlassian.net/browse/DX-2490" title="DX-2490" target="_blank">TaskDX-2490</a>  `state update lock` should also disable auto updates
  </td></table>
  <br />

### CODE REVIEW

**Review by Naatan — CHANGES_REQUESTED** [review]
This should be addressed by `state update lock` toggling the `autoupdate` config var.

https://github.com/ActiveState/cli/blob/3d2b9f229323765b5e9c9b93c7179f613fbb2126/cmd/state/autoupdate.go#L37-L37

**Comment by mitchell-as** [comment]
I'm not sure how I feel about that, given that we're changing a universal configuration option for a project-specific setting. If you were to unlock the project, is it supposed to re-enable the auto update option? What if I've explicitly set `state config set autoupdate false` prior to lock/unlock?

**Comment by Naatan** [comment]
> I'm not sure how I feel about that, given that we're changing a universal configuration option for a project-specific setting. If you were to unlock the project, is it supposed to re-enable the auto update option? What if I've explicitly set `state config set autoupdate false` prior to lock/unlock?

I share your reservations, but Pete made the call after I shared them with him. 

@rawktron fyi. 

I think it might be good for us to review the use-cases here again and find a good solution for them, even if it means breaking the current command (which this is kinda already doing).

Anyway, this isn't a blocker for landing this ticket. As I said Pete and I already discussed, don't want to keep going back on decisions made, just tagging Pete here since you also raised the concern @mitchell-as.

**Review by Naatan — CHANGES_REQUESTED** [review]
Looks good, but needs error checks on `cfg.Set()`.

**Review by Naatan — APPROVED** [review]

**Pull request merged**
