### PR TITLE
Do not attempt to setup environment for DisabledRuntime.

### PR DESCRIPTION
**Pull request by mitchell-as**
<table>
<td>
  <a href="https://activestatef.atlassian.net/browse/DX-1008" title="DX-1008" target="_blank">BugDX-1008</a>  runtime panic "getenvbasedon"
  </td></table>
  <br />

### CODE REVIEW

**Review by Naatan — CHANGES_REQUESTED** [review]
This looks good, however I'd like to take the opportunity to make this code a little more robust and obvious.

I noticed when we "disable" the runtime we just pass around an essentially empty Runtime struct:

https://github.com/ActiveState/cli/blob/6aa8d11a7d27c8fca58c61950ebb1ae6fcb771c0/pkg/platform/runtime/runtime.go#L73

I think instead we should have something explicit (eg. a property `disabled: true`), which we then check for explicitly when doing eg. an update, and cancel out early.

This should hopefully prevent issues like this in the future. The issue being that the disabled behaviour is really implicit at the moment, and easy to miss while making changes.

**Comment by mitchell-as** [comment]
The integration test actually uncovered a bug. `updateArtifacts()` needs to return a list of all *required* artifacts for the runtime, not just the artifacts that *were installed*.

**Review by Naatan — CHANGES_REQUESTED** [review]
Nice work finding that other bug! But could you please separate this into its own PR? Reason being; when I check release notes or cherry pick PRs for a new release I won't be able to tell that this one contains a fix unrelated to it. I've filed a story for this here: https://activestatef.atlassian.net/browse/DX-1019

**Comment by mitchell-as** [comment]
Okay, that makes sense. I've reverted the most recent commits and left the stuff we talked about on Zoom.

**Review by Naatan — APPROVED** [review]

**Pull request merged**
