### PR TITLE
Build a more portable state-exec on Linux

### PR DESCRIPTION
**Pull request by mitchell-as**
<table>
<td>
  <a href="https://activestatef.atlassian.net/browse/DX-1126" title="DX-1126" target="_blank">BugDX-1126</a>  SHELL/ACTIVATE: Linux - any attempt to activate the project `use` or `activate` we have error message `Illegal instruction (core dumped)`
  </td></table>
  <br />

### CODE REVIEW

**Comment by Naatan** [comment]
I just said this as speculative on Slack, we should probably discuss/investigate before we action removing UPX. Though removing it for state-exec definitely makes sense as we had never evaluated it for zig.

**Comment by mitchell-as** [comment]
I'm only testing to see if CI is to blame here.

**Review by daved — CHANGES_REQUESTED** [review]
Let's also be explicit with the Mac build: `-target "x86_64-macosx"`

**Comment by mitchell-as** [comment]
Good call.

**Review by daved — APPROVED** [review]

**Pull request merged**
