### PR TITLE
Do not add State's bin path to $PATH again after install process.

### PR DESCRIPTION
**Pull request by mitchell-as**
<table>
<td>
  <a href="https://activestatef.atlassian.net/browse/DX-820" title="DX-820" target="_blank">BugDX-820</a>  CLI - STATE INSTALL: Same path added twice to the PATH env variable
  </td></table>
  <br />
 

It will already show up in the subshell due to the shell rc file being updated during installation.

### CODE REVIEW

**Comment by mitchell-as** [comment]
I'm not sure how to test this. I've tried to run the installer build artifacts, but it's not doing what the real installers do.

**Comment by mitchell-as** [comment]
With an official installer, I get this output with `VERBOSE=1`:

```
(PID 3258) [DEBUG Apr  5 14:34:34.319508900, exeutils.go:100] ExecSimpleFromDir: dir: , bin: /root/.local/ActiveState/StateTool/release/bin/state, args: [_prepare]
✔ Done

(PID 3258) [DEBUG Apr  5 14:34:35.294490300, installer.go:112] Installation was successful
█ State Tool Package Manager Installation Complete

State Tool Package Manager has been successfully installed.
(PID 3258) [DEBUG Apr  5 14:34:35.296426200, subshell.go:99] Detected SHELL: bash
(PID 3258) [DEBUG Apr  5 14:34:35.296490400, subshell.go:131] Using binary: /usr/bin/bash
(PID 3258) [DEBUG Apr  5 14:34:35.296533400, sscommon.go:40] Starting subshell with cmd: /usr/bin/bash
```

With a GitHub Actions installer, all I get is:

```
(PID 3345) [DEBUG Apr  5 14:38:03.765877000, exeutils.go:100] ExecSimpleFromDir: dir: , bin: /root/.local/ActiveState/StateTool/mitchell/dx-820/bin/state, args: [_prepare]
(PID 3345) [DEBUG Apr  5 14:38:05.145399700, installer.go:118] Installation was successful
✔ Done
```

**Review by MDrakos — CHANGES_REQUESTED** [review]
This makes sense. Can we just run the `update` integration tests to just ensure there isn't something we're missing? They should be passing on master though you may need to merge it in.

**Comment by mitchell-as** [comment]
I think the new single-service stuff that was recently merged onto master is causing the update tests to still fail.

**Comment by mitchell-as** [comment]
The only installer failure is not related to these changes.

**Comment by mitchell-as** [comment]
Yes, https://activestatef.atlassian.net/browse/DX-850 and https://github.com/ActiveState/cli/pull/1802

**Pull request merged**
