### PR TITLE
Do not update to merge commit if there was a buildscript conflict.

### PR DESCRIPTION
**Pull request by mitchell-as**
<table>
<td>
  <a href="https://activestatef.atlassian.net/browse/DX-2842" title="DX-2842" target="_blank">BugDX-2842</a>  Merge commit and manual conflict created at same time
  </td></table>
  <br />
 

This partially reverts #3249 because that solution was based on the buggy behavior fixed in #3282.

### CODE REVIEW

**Review by Naatan — CHANGES_REQUESTED** [review]
I would expect to see extra logic here. There's two scenario's this needs to cover:

1. There was a conflict that needs to be manually resolved, in this case the commit should be set to the commit ID of the remote project (ie. not a newly created merge commit).
2. There was a conflict which was automatically resolved, in this case the commit should be set to the merge commit. If a buildscript conflict occurs then we are in scenario 1, not 2.

Only one of these scenarios can be true at a time.

I think your current changes are only facilitating scenario 2.

**Comment by mitchell-as** [comment]
Yeah, I think you're right. At this point, I've done so many iterations of this that I'm easily confused. Hopefully I've gotten a hold of this.

**Comment by mitchell-as** [comment]
The lone test failure is a performance unit test failure unrelated to this PR.

**Review by Naatan — APPROVED** [review]
I think you got it, but yeah pretty heady so we'll see if this passes by Mark 😅 Nice work!

**Pull request merged**
