### PR TITLE
Remove works from MSI menu

### PR DESCRIPTION
**Pull request by mdrohmann**
https://www.pivotaltracker.com/story/show/174482706

### CODE REVIEW

**Comment by mdrohmann** [comment]
At least on Windows 8.1, the properties that I now tagged as secure, were previously ignored with the log message: `Ignoring disallowed property XYZ`.  This has something to do with the client/server architecture of MSIs: only secure properties are allowed to be moved to the server.

I cannot say that I understand it, but this fixes the problem.

**Comment by mdrohmann** [comment]
That's taken care of. :)

**Comment by Naatan** [comment]
Did you verify that this fixes the issue on Windows 10? That's where I got the issue.

**Comment by mdrohmann** [comment]
I could only reproduce it on Windows 8.1. On Windows 10 it always worked. @Naatan Can you try on your machine once this is merged?

**Pull request merged**
