### PR TITLE
Do not report silent installer errors to Rollbar.

### PR DESCRIPTION
**Pull request by mitchell-as**
<table>
<td>
  <a href="https://activestatef.atlassian.net/browse/DX-2862" title="DX-2862" target="_blank">BugDX-2862</a>  Silenced errors should not be reported to rollbar
  </td></table>
  <br />
 

There is a question of how we want to report silent errors to analytics. Right now, it reports "error" to the CatInstaller label, and "fail" to the CatInstallerFunnel label. If this is okay, then no further action is needed. Otherwise, please let me know.

### CODE REVIEW

**Review by Naatan — CHANGES_REQUESTED** [review]
I think it makes more sense to place this conditional here:

https://github.com/ActiveState/cli/blob/master/internal/runbits/errors/errors.go#L227-L227

That way we still get the analytic events, just not the rollbar one.

**Comment by mitchell-as** [comment]
That's interesting. So should we file a ticket to change our error reporting in state/main.go? https://github.com/ActiveState/cli/blob/927624eb09bd6ea9c34260b468a422fe1044fc66/cmd/state/main.go#L255-L263 `errors.ReportError()` is not being called at all if it's a silent error.

**Comment by Naatan** [comment]
Hmm yeah this is a bit of a mess right now. I'd like to refactor this altogether, but not right now for this story.

I see some obvious wins that we can make within the context of this story, on top of the current changes I would suggest:

- Drop the IsSilent here: https://github.com/ActiveState/cli/blob/master/cmd/state/main.go#L255-L255
	- This ought to be a concern of ReportError, which your current changeset is addressing.	
- Drop the manual reporting here: https://github.com/ActiveState/cli/blob/master/cmd/state-remote-installer/main.go#L166-L172
	- This is entirely redundant with what ReportError does.

**Review by Naatan — CHANGES_REQUESTED** [review]
Looks good, but given our findings in our ticket I'd also like to make the changes outlined here:

https://github.com/ActiveState/cli/pull/3330#issuecomment-2136125707

**Review by Naatan — APPROVED** [review]

**Pull request merged**
