### PR TITLE
Revert runtime in use checking.

### PR DESCRIPTION
**Pull request by mitchell-as**
<table>
<td>
  <a href="https://activestatef.atlassian.net/browse/DX-2472" title="DX-2472" target="_blank">BugDX-2472</a>  `state checkout` has awkward pause
  </td></table>
  <br />

### CODE REVIEW

**Comment by mitchell-as** [comment]
Test failure is not due to this PR.

**Comment by Naatan** [comment]
@mitchell-as this issue only started happening for me around the time we started work on v0.44. Whereas this functionality you're updating here hasn't been touched in quite a while (afaik?). Are you sure this isn't a red herring?

My thought was that this slowdown is likely caused by the change in buildplan sourcing needed for dependency calculation.

**Comment by mitchell-as** [comment]
@Naatan No, I confirmed that it's caused by the runtime in use checking introduced recently. It's a macOS-only issue and the telltale sign is Terminal.app changing the tab label to `lsof` during the pause.

**Comment by mitchell-as** [comment]
Closing in favor of #3088

**Pull request closed without merging**
