### PR TITLE
Use tier description as title instead of tier name

### PR DESCRIPTION
**Pull request by daved**
https://www.pivotaltracker.com/story/show/178506035

### CODE REVIEW

**Comment by daved** [comment]
The only file of interest for this PR is "internal/runners/organizations/organizations.go".

**Comment by daved** [comment]
A few more files have been touched to resolve breakages.

**Review by mdrohmann — APPROVED** [review]
LGTM

**Review by Naatan — CHANGES_REQUESTED** [review]
I'm a little concerned with the inventory api and vendor changes. Nothing that's changing here should necessitate any changes in those components.

**Comment by daved** [comment]
Fixed.

**Review by Naatan — APPROVED** [review]

**Pull request merged**
