### PR TITLE
Minimize failed file removal logging in moveallfilesrecursively

### PR DESCRIPTION
**Pull request by daved**
https://www.pivotaltracker.com/story/show/179628286

### CODE REVIEW

**Comment by daved** [comment]
"only reported once per runtime invocation"
This solution reports only once per MoveAllFilesRecursively call. Something more directly tied to runtime invocations will require more complexity. Please let me know if I should take that approach.

**Review by mdrohmann — COMMENTED** [review]
I realized that we might not need this even.  On the release branch, the `if err != nil` check isn't there yet.  So, we get the message even if the `os.Remove` block succeeds! 

https://github.com/ActiveState/cli/blob/release/internal/fileutils/fileutils.go#L493-L494

All the rollbar errors that I looked at actually report the error as `<nil>`.

**Comment by mdrohmann** [comment]
So, I think we should make sure that this PR gets into release: https://github.com/ActiveState/cli/pull/1532

**Comment by daved** [comment]
Closing in favor of #1564

**Pull request closed without merging**
