### PR TITLE
Merge "PATH" with Window's "Path".

### PR DESCRIPTION
**Pull request by mitchell-as**
<table>
<td>
  <a href="https://activestatef.atlassian.net/browse/DX-3012" title="DX-3012" target="_blank">BugDX-3012</a>  Windows - `state exec` regression
  </td></table>
  <br />
 

This enables searching for exes in not just runtime PATH, but also Windows Path.

I believe this PR triggered the issue: https://github.com/ActiveState/cli/commit/d881640f32db1ffb3fb488a2b87f860cd6c82374, but I think it exposed the fact we aren't merging `PATH` and `Path` on Windows.

### CODE REVIEW

**Comment by mitchell-as** [comment]
I believe this PR triggered the issue: https://github.com/ActiveState/cli/commit/d881640f32db1ffb3fb488a2b87f860cd6c82374, but I think it exposed the fact we aren't merging `PATH` and `Path` on Windows.

**Comment by mitchell-as** [comment]
Test failures are not due to this PR.

**Review by Naatan — CHANGES_REQUESTED** [review]
I may lack context here, but intuitively this feels wrong to me. If Windows is case insensitive then setting it to the sensitivity windows "assumes" doesn't solve anything. It sounds like the issue stems from us treating PATH as case sensitive on Windows, when it is not.

I think we need to make a larger change that has us always use `Path` on Windows for consistency, but also has us respecting case insensitive PATH matches.

It seems that this was always "broken" and we're just now realizing, right? So perhaps fixing the bug at hand at filing a story for a larger refactor is appropriate here. ie. your proposed solution for updating JUST `state exec`.

**Comment by mitchell-as** [comment]
Okay, I've worked around this and filed DX-3030 in response.

**Comment by mitchell-as** [comment]
Test failures are unrelated to this PR.

**Review by Naatan — APPROVED** [review]

**Pull request merged**
